### ISSUE TITLE
Tests not passing due to them being outdated + test refactoring.

### ISSUE THREAD

**Issue by fonsocarre** [ImperialCollegeLondon/sharpy#11]
I've been working on [dev_cleanup](https://github.com/ImperialCollegeLondon/sharpy/tree/dev_cleanup) ahead of the release of the very first decent SHARPy version.
The last commit of the big series of work is 354eeb7a7145cbd2bf4defd0d4890bf36eef2d8f.

A very large number of tests fail due to them not being up to date.
I'm fixing all the test suite so that it looks halfway decent. Now `tests` is only for
tests. `cases` will contain the HALE, X-HALE, Type01, Flying wing, etc.

`tests/coupled/prescribed` still has a ton of different cases.

Problems I've found:
- [x] `tests.utils.generate_cases_test.TestGenerateCases.test_generate_wt_excel_type01` (not found file: `database_type01.xslx`).
- [ ] `tests.linear.uvlm.infinite_span_test` runs, but throws a million warnings. Also, somebody with an IDE, please reformat it. - @ngoiz 
- [x] The `multibody` cases throw a lot of garbage on screen when running (Generating an instance of...). Plus the two Type01 throw errors on execution.
- [x] `tests.coupled.prescribed.gamma_dot_test` diverges and breaks the execution of the test suite (I'm commenting that one, but we need to fix it). When this is fixed, just add a `__init__.py` empty file in `tests/coupled/prescribed/gamma_dot_test/`. - @ngoiz 
- [x] Remove the warnings in the `TestGenerateCases` test.
- [x] `tests.coupled.multibody.double_pendulum` needs to cleanup after execution (check `TestGenerateCases` on how to do it).
- [x] `tests.coupled.multibody.double_pendulum` takes too long. I've shortened, but is probably not good enough (I also haven't updated the reference values).

I've also removed all the print statements in the testing suite. It just made a mess.
The names of the test files NEED to be `test_<something>.py` to be acknowledged by `unittests`.

If you can do some of these, I'll slowly work around the code to polish it.

**Comment by ArturoMS13** [comment]
I have fixed the test related to the multibody and the generate cases

**Comment by fonsocarre** [comment]
I fixed a number of cases in the new pull request to `develop`. However, there are still things that I don't like:
- [ ] The `generate_cases` library writes different default values for the structural solver depending on from where the test is being called. For example the `fixed_node_velocity_wrtG` case has `gravity_on == True` or `False` depending on if the tests are called for the whole project (`python -m unittest`) vs the test file only (`python -m unittest tests/..../test_fixed_node_velocity_wrtG.py`).
- [ ] I added a `skip` to the `linear.uvlm` tests because all those tests need updating.

Passing the tests will be a much more important topic, as I am moving `develop` to a pull request-only branch, which means that every merge needs to be approved AND the travis tests need to pass in order to be included.

**Comment by ArturoMS13** [comment]
Hi! 
I have tried to replicate the first one of the issues but I cannot. However, I also get a small difference when running the cases like that. 
I have fixed it in the dev_lagrange-static branch. I think I was overwriting the solvers dictionary with the generate cases library.
Can someone test it?
Thanks

**Comment by ArturoMS13** [comment]
Hi!
I have tried to replicate the first one of the issues but I cannot. However, I also get a small difference when running the cases like that.
I have fixed it in the dev_test_gen_cases branch. I think I was overwriting the solvers dictionary with the generate cases library.
Can someone test it?
Thanks

**Comment by fonsocarre** [comment]
I'll try to test it ASAP, thanks!

**Comment by fonsocarre** [comment]
It worked, all good now.
