### ISSUE TITLE
Simulation of some new configuration (e.g., box-wings or Joined wing)

### ISSUE THREAD

**Issue by LeeElvis** [ImperialCollegeLondon/sharpy#110]
Hi, I'm doing some research on the aeroelasticity property of **a joined wing configuration**, and not sure if SHARpy can do those simulations of such configurations and which module should be involved, or if it can't, could you give me some idea which code I should work on to accomplish this? I think most probably is the structural module. Great appreciate for any help.

**Comment by ArturoMS13** [comment]
Dear LeeElvis,

thank you for your interest on SHARPy.

We have not built a box-wing so far. However, we already have examples of configurations with several lifting surfaces that interact among them:
     - https://ic-sharpy.readthedocs.io/en/develop/content/example_notebooks/nonlinear_t-tail_HALE.html
     - Del Carre, A., Deskos, G., & Palacios, R. (2020). Realistic turbulence effects in low altitude dynamics of very flexible aircraft. In AIAA SciTech Forum (pp. 1–18). https://doi.org/10.2514/6.2020-1187

Moreover, the code allows the simulation of complex structures as long as they are build as a collection of slender beams. Thus, I think you should be able to generate that geometry. I would advise you to have a look at the documentation and specifically to these two pages:
     - https://ic-sharpy.readthedocs.io/en/develop/content/example_notebooks/nonlinear_t-tail_HALE.html
     - https://ic-sharpy.readthedocs.io/en/develop/content/casefiles.html

The modules you would need to use depend on the type of simulation you want to do: flight dynamics, linear analysis such as frequency response ...

Best regards, Arturo.

**Comment by LeeElvis** [comment]
Dear Arturo,

Very thanks for your help, I'll try this simulation.

Best regards, Elvis.

**Comment by ArturoMS13** [comment]
Hi, I am closing this issue.
Feel free to open it again if you need any further help or to show us the results of your simulation. 
Best regards, Arturo
