### ISSUE TITLE
Bug in beamstructure.py

### ISSUE THREAD

**Issue by LeeElvis** [ImperialCollegeLondon/sharpy#117]
Hi, there is a small bug in the following py, the member 'tangent_vector_def' is not defined in the class 'Element'.
https://github.com/ImperialCollegeLondon/sharpy/blob/6dc2353b9d5f29c46a44f90ed5e7b5b7520e892b/sharpy/structure/models/beamstructures.py#L76

**Comment by ArturoMS13** [comment]
Hi LeeElvis, thank you for reporting it. 

I hope this bug is not causing big troubles because this function is not called anywhere in the code.

I will look into it asap.

**Comment by ArturoMS13** [comment]
I have removed this function because it is not used anywhere in the code and I cannot figure out what it does to fix it.
