### ISSUE TITLE
Why no pip support?

### ISSUE THREAD

**Issue by DavidAnderegg** [ImperialCollegeLondon/sharpy#171]
Hi all
thank you for open sourcing this.

I just recently installed SHARpy and it seems a bit odd to me that you don't have a `setup.py`file. As far as i understand, the whole stuff lives in the folder i cloned and is made available through the `sharpy_vars.sh`. Is there a specific reason you dont want to install it into the anaconda directory and make it available system wide without this script?

Maybe i misunderstood something? Could you clarify this?

If there is no specific reason, i would look into it.

**Comment by ngoiz** [comment]
Hi David,

That's certainly a very valid point. I take it that we started off with this `sharpy_vars.sh` approach and never really thought about using pip or conda builds (and to be completely honest, it is not my area of expertise). What we like (or at least what I sometimes do) about the current approach is that we can quickly change between SHARPy builds when developing new features. In my case I have a directory where I have my simulation scripts and then may change between a release version of SHARPy and another when I'm trying out some new stuff.

If you think SHARPy would benefit from pip support please feel free to look into it, I guess that's the real beauty of open source!

Thanks,
-Norberto

**Comment by ngoiz** [comment]
Maybe @ArturoMS13 or @fonsocarre also have some insight

**Comment by DavidAnderegg** [comment]
Hi Norberto

Thank you for the answer. I would be happy to contribute in this way and will look into it.

What you are saying about different builds could then be accomplished with different anaconda environments. You could have a `sharpy` and a `sharpy_dev` environment for example. Additionally, there would be some sort of version control for the end user.

**Comment by ngoiz** [comment]
Hi David,

It sounds like a feature SHARPy would definitely benefit having! If you have time and look at it we would greatly appreciate it.

Keep us posted. Many thanks!
