### ISSUE TITLE
Potential Issue in the balancing direct method

### ISSUE THREAD

**Issue by AntonioWR** [ImperialCollegeLondon/sharpy#183]
**Describe the bug**
In sharpy/rom/balanced.py, In the ''Direct'' class of balancing method, after S, T, Tinv are calculated by the method in librom.py.  The reduced state space matrix Ar, Br, Cr are calculated as:
Ar = T.dot(A.dot(Tinv))
Br = T.dot(B)
Cr = C.dot(Tinv)
I wonder if it should be:
Ar = Tinv.dot(A.dot(T))
Br = Tinv.dot(B)
Cr = C.dot(T)

I have used the direct method and the build-in frequency response function (in libss.py) to compare the Reduced-order state-space system with the full model.
The difference in frequency response does not decrease by increasing the number of states deployed. (i.e. a higher-order model)
By cross-validation with the literature and the iterative method, the code that I suggested above provides the correct result. 

**To Reproduce**
I am using the Goland wing template given in the example (https://ic-sharpy.readthedocs.io/en/master/content/examples.html).
I have compared the direct balancing method with the rest of the ROM.

If model related, please try and reproduce with one of the provided models (found in `/cases/`). Else, please provided the input files (a `.fem.h5`, `aero.h5` and `case.sharpy`).

**Expected behavior**
The frequency response of the reduced model should be close to the full model.

**Screenshots**

**System Info (please complete the following information):**
 - OS: Ubuntu 20.04.3 LTS
 - SHARPy Version 1.3

**Additional context**

**Comment by ngoiz** [comment]
Hi Antonio,

I think you are right, many thanks for raising this. It should be a quick fix.

Many thanks,
Norberto
