### ISSUE TITLE
Wrong key in settings for /cases/templates/flying_wings.py

### ISSUE THREAD

**Issue by ianlamfar** [ImperialCollegeLondon/sharpy#205]
Line 598 of `/cases/templates/flying_wings.py` currently has a wrong key of `'clean_up_previous_solution'`. It should be `'cleanup_previous_solution'`.

**Comment by sduess** [comment]
Dear Chit Yuen Lam,

many thanks for pointing this out. I have already opened a pull request to correct this typo which should be merged into the develop branch soon. 

Cheers,
Steffi
