### ISSUE TITLE
Potential bug in /sharpy/structure/utils/modalutils.py

### ISSUE THREAD

**Issue by LeeElvis** [ImperialCollegeLondon/sharpy#208]
**Describe the bug**
Hi, there exists a small bug at line 289 in `/sharpy/structure/utils/modalutils.py`:
`for mode in range(num_rigid_body, NumLambda - num_rigid_body):` should be `for mode in range(num_rigid_body, NumLambda )`.
Thank you.

**Comment by LeeElvis** [comment]
Hi, another potential bug was found in `sharpy/postproc/aeroforcescalculator.py`, the function of `file_output`: `force_matrix` and `moment_matrix`  are mismatched with the following code in that function, which may cause confusion in the output file 'aeroforces.txt'.
Thank you.

**Comment by sduess** [comment]
Thanks @LeeElvis for spotting that. Both have recently been fixed in #273.
