### ISSUE TITLE
Solving Environment gets killed.

### ISSUE THREAD

**Issue by aash-r** [ImperialCollegeLondon/sharpy#268]
OS: Ubuntu 22.04.3
I installed Anaconda, Git and Gfortran. The conda environment was activated. 
(base) root@chevron:

I cloned the repository and followed the steps as mentioned on the website:

(base) root@chevron:/home/SHARPy# cd sharpy/utils
(base) root@chevron:/home/SHARPy/sharpy/utils# conda env create -f environment.yml
Collecting package metadata (repodata.json): done
Solving environment: \ Killed

**Comment by kccwing** [comment]
Hello @aash-r, thanks for using SHARPy! How much RAM do you have on your Ubuntu machine/VM? Right now we recommend at least 16GB of RAM for conda to solve the environment properly. We are investigating and will be patching this soon - if you don't have access to extra RAM could you please use v2.1 for now? Thanks!

**Comment by aash-r** [comment]
Thank you reaching out. I will try increasing the RAM allocation to my virtualbox and try out v2.1 if the issue still persists. Thank you!

**Comment by aash-r** [comment]
Hi @kccwing, increasing RAM works. The solving environment was complete. Thank you!

**Comment by kccwing** [comment]
No worries, thank you very much @aash-r!
