### ISSUE TITLE
BeamLoader postprocessor squishing answers

### ISSUE THREAD

**Issue by GregorWilson** [ImperialCollegeLondon/sharpy#270]
**Describe the bug**
The beamloader postprocessor appears to be squishing its results into an array only half the length of the structural nodes. This happens for loads, strains, coords, etc.

**To Reproduce**
On any simulation where the beamloader is active just have a look at the length of the postprocessor 'loads' array vs the # of structural nodes. I believe you should see the 'loads' array is half that of the # of structural nodes. This is also true for all other postprocessor results i.e. strain)

**Expected behavior**
I believe the beamloader postprocessor should output its loads, strains, etc. to an array that corresponds to each structural node. 

**Screenshots**
![strangeforces](https://github.com/ImperialCollegeLondon/sharpy/assets/123393183/e74b1a71-61f2-49d8-8b46-4bc5b07dc6eb)

**System Info (please complete the following information):**
 - OS: imperial typhoon aeronautics server - Operating System: Debian GNU/Linux 12 (bookworm), Kernel: Linux 6.1.0-12-amd64
 - SHARPy v2.0

**Additional context**
Was mentioned at the sharpy weekly meeting on 1/11/23, this is the reason for strange bending moment distributions along wings

**Comment by ben-l-p** [comment]
Hi Gregor,

I believe that the beam loader outputs values per element, not per node (of which there are around half as many), which should explain why this is the case. Please see the relation below from the docs:

*  ``num_elem [int]`` : number of structural elements.

*  ``num_node [int]`` : number of nodes.

   For simple structures, it is ``num_elem*(num_node_elem - 1) - 1``.
   For more complicated ones, you need to calculate it properly.

**Comment by GregorWilson** [comment]
yup that makes sense, I just assumed it output loads at nodes so I'll close.

Thanks for responding!
