### ISSUE TITLE
Scipy 1.12.0 Incompatible

### ISSUE THREAD

**Issue by SJ-Innovation** [ImperialCollegeLondon/sharpy#276]
**Describe the bug**
scipy.fftpack has been deprecated since 1.14.x, attempting to run with scipy 1.12.x results in import failure of "ifft" from scipy. 

**To Reproduce**
Clean build a Docker image runtime environment using current environment.yml which does not provide version compatibility information, attempt to run, ImportError. 

**Solutions**
Either add version compatibility information to environment.yml file, or update entire codebase to scipy 1.12.x 
PR for initial hotfix in progress.

**Comment by kccwing** [comment]
Thanks @SJ-Innovation for spotting this! We will be addressing this in our next bug fix.

**Comment by ben-l-p** [comment]
Issue should be fixed with the recent change to pip install [HERE](https://github.com/ImperialCollegeLondon/sharpy/pull/280), which updated the code to use the new FFT library. Any "recent" version of SciPy from the last few years should work fine.
