### ISSUE TITLE
Not a Git Repository

### ISSUE THREAD

**Issue by p-smith22** [ImperialCollegeLondon/sharpy#295]
**Describe the bug**
Whenever I try to run the test case in the Sharpy v2.3 installation guide, I get the following error:
`fatal: not a git repository (or any of the parent directories): .git`
I have tried to troubleshoot this using `git init`, and checked that there even was a .git using `ls -a` (.git was present). 

**To Reproduce**
```
Install cmake, g++, gfortran, etc.
git clone --recursive http://github.com/ImperialCollegeLondon/sharpy
cd sharpy
pip install .
```
Automated test yields (this was with the changes made to generate_geradin.py outlined in "2. Results (part 1)":
```
Ran 90 tests in 154.345s

FAILED (errors=1, skipped=4, expected failures=1)
```
With the error being: 
`ERROR: test_geradin (tests.xbeam.test_xbeam.TestGeradinXbeam.test_geradin)`

**Expected behavior**
Expected behavior was for the example code to run as outlined in the installation guide. I just wanted to ensure the package was correctly installed before proceeding into more complicated models, but I cannot get the example case to run. 

**System Info (please complete the following information):**
 - MacOS Sonoma 14.6.1
 - SHARPy version 2.3

**Comment by p-smith22** [comment]
Downloaded a clean copy and it eliminated the error. Also realized this is not actually a fatal mistake, the output files are still generated and match the results in the code.

**Comment by kccwing** [comment]
Hello @p-smith22, welcome and thanks for raising and resolving this! Glad to know it's all working fine now.
