### ISSUE TITLE
Creating aileron control surfaces to induce roll

### ISSUE THREAD

**Issue by p-smith22** [ImperialCollegeLondon/sharpy#304]
Hello. This is not a bug but simply a question regarding SHARPy. Is there any way to create an aileron configuration to induce roll in the model? I have currently mapped out the ailerons onto the main wings in roughly the correct spot and the run is simulating using the StaticCoupled bypass, but the behavior is not as expected. The model seems to react to the deflection inputs but does not induce a roll, rather maneuvers/yaws left or right. Is it possible to induce a roll? If so, is there a particular way to do so efficiently, perhaps a dynamic force moment on the model?
Thanks!

**Comment by ben-l-p** [comment]
Are the ailerons moving as you would expect from looking at the aerodynamic grid? It would be possible also to achieve a rolling moment with opposing dynamic forces on each wing - if this is any use depends on what you are hoping to achieve.
