### ISSUE TITLE
Compare to other competing software in JOSS paper

### ISSUE THREAD

**Issue by petebachant** [ImperialCollegeLondon/sharpy#36]
From https://github.com/openjournals/joss-reviews/issues/1885.

>**State of the field:** Do the authors describe how this software compares to other commonly-used packages?

**Comment by fonsocarre** [comment]
@rafapalacios Which software packages would you include here as directly related? I can think of ZAERO, UM/NAST (none of them Open Source), and I guess OpenFast for WT aeroelasticity. Any input?

**Comment by rafapalacios** [comment]
For aircraft application, ASWING (http://web.mit.edu/drela/Public/web/aswing/) is the only one with some online support, although you need to license it from MIT. ZAERO is an aerodynamic tool and it is full proprietary; and UM/NAST is a research code only referred to in papers.
For wind turbines, OpenFAST (https://github.com/openfast) and HAWC2 http://www.hawc2.dk/, cover a similar space, although they are both built using simple aerodynamics.

**Comment by fonsocarre** [comment]
Thanks @rafapalacios, more or less what I thought. I'll write a paragraph about it and give you a shout when it is done in the pull request.
