### ISSUE TITLE
Considerations for building SHARPy

### ISSUE THREAD

**Issue by rafmudaf** [ImperialCollegeLondon/sharpy#47]
### Cross Platform
Have you considered using a build system like CMake to support cross-platform compiling? On the surface, this project seems small enough that creating a CMake project would be simple and straightforward. There are also other alternative build systems like [Bazel](https://bazel.build).

### git-submodule for linking projects
Rather than manually copying files between projects and assuming a directory structure, you might consider linking UVLM and XBeam into SHARPy as git-submodules. If you use a more robust build system, you could even link the projects into each other so that they build in one shot. Git-submodules do have some downsides, but I think your project is a great use case for this.

---

I know software projects can be nuanced and some of these more automated solutions might not work. However, if you'd like to chat about any of this in detail, I'm happy to schedule a meeting to talk and get any of this started.

**Comment by ngoiz** [comment]
Great suggestions, @rafmudaf. Linking uvlm and xbeam does sound like a job for git-submodules given our dependency on them. I'll have a look into the implementation. As for the cross-platform compiling, our expert @fonsocarre will know a lot more than me on how to implement.

I appreciate the meeting offer! We'll do some reading on our end and may take you up on that! 

Thanks!
