### ISSUE TITLE
WindTurbine case generation script does not produce sharpy file

### ISSUE THREAD

**Issue by petebachant** [ImperialCollegeLondon/sharpy#50]
Running in Docker container for https://github.com/openjournals/joss-reviews/issues/1885.

The HDF5 files appear to be created correctly, but I don't get a case file.

**Comment by ArturoMS13** [comment]
Hi Pete,

If the problem is with `coupled/WindTubine` I get your point because it generates the file with the legacy name `rotor.solver.txt`. I will update it to `rotor.sharpy`. The legacy case still works as `sharpy rotor.solver.txt`.

If it is with another case, please let me know. 

Thank you!
