### ISSUE TITLE
Minor documentation issues

### ISSUE THREAD

**Issue by rafmudaf** [ImperialCollegeLondon/sharpy#53]
These sections of the docs are outdated or broken.

- https://ic-sharpy.readthedocs.io/en/latest/content/sharpy_intro.html#SHARPy-installation (remove this section all together in favor of the installation section?)
- https://ic-sharpy.readthedocs.io/en/latest/includes/aero/models/aerogrid/generate_strip.html
 Doesn't render as expected based on the other API docs

**Comment by ngoiz** [comment]
Hi @rafmudaf!

Indeed, the SHARPy guide we had was initially tailored to get our students up and running quickly but I think at this point the rest of the documentation has grown to include all content. I’ll restructure it to ensure everything is captured in the appropriate sections. I’ll also check the aerogrid docs.

Thanks for the review!
