### ISSUE TITLE
Broken link on SHARPy Installation Guide

### ISSUE THREAD

**Issue by yanjinh** [ImperialCollegeLondon/sharpy#67]
The link to the SHARPy Github repository on the installation guide is broken and is: 
[https://github.com/imperialcollegelongon/sharpy]

I believe the actual link is:
[https://github.com/ImperialCollegeLondon/sharpy]

**Comment by ngoiz** [comment]
Thanks! I’ll update the guide and fix that (as well as some other improvements)
