### ISSUE TITLE
lingebm.py -> update_matrices_time_scale

### ISSUE THREAD

**Issue by outoforderdev** [ImperialCollegeLondon/sharpy#69]
When 'ScalingDict' defaults to {} in 'LinearAssembler' settings (i.e. not set):

```    
ws.config['LinearAssembler'] = {'linear_system': 'LinearAeroelastic',
                                    'linear_system_settings': {
                                        'beam_settings': {'modal_projection': 'off',
                                                          'inout_coords': 'nodes',
                                                          'discrete_time': 'on',
                                                          'newmark_damp': 0.5e-4,
                                                          'discr_method': 'newmark',
                                                          'dt': ws.dt,
                                                          'proj_modes': 'undamped',
                                                          'use_euler': 'off',
                                                          'num_modes': par.num_modes,
                                                          'print_info': 'on',
                                                          'gravity': 'on',
                                                          'remove_sym_modes': 'on',
                                                          'remove_dofs': []},
                                        'aero_settings': {'dt': ws.dt,
                                                          # 'ScalingDict': {'length': 0.5 * ws.c_ref,
                                                          #                 'speed': par.u_inf,
                                                          #                 'density': par.rho},
                                                          'integr_order': 2,
                                                          'density': ws.rho,
                                                          'remove_predictor': 'on',
                                                          'use_sparse': 'off',
                                                          'rigid_body_motion': 'off',
                                                          'use_euler': 'off',
                                                          'remove_inputs': ['u_gust'],
                                                          # 'rom_method': ['Krylov'], 'rom_method_settings': {
                                                          # 'Krylov': rom_settings}
                                                          },
                                        'rigid_body_motion': False}} 
```

lingebm.py -> update_matrices_time_scale returns:

```
Traceback (most recent call last):
  File "main.py", line 79, in <module>
    sharpy.sharpy_main.main(['', ws.route + ws.case_name + '.sharpy'])
  File "/home/mpc/sharpy/sharpy/sharpy_main.py", line 124, in main
    raise e
  File "/home/mpc/sharpy/sharpy/sharpy_main.py", line 100, in main
    data = solver.run()
  File "/home/mpc/sharpy/sharpy/postproc/asymptoticstability.py", line 189, in run
    self.velocity_analysis()
  File "/home/mpc/sharpy/sharpy/postproc/asymptoticstability.py", line 250, in velocity_analysis
    ss_aeroelastic = self.data.linear.linear_system.update(u_inf_vec[i])
  File "/home/mpc/sharpy/sharpy/linear/assembler/linearaeroelastic.py", line 274, in update
    self.beam.sys.update_matrices_time_scale(t_ref)
  File "/home/mpc/sharpy/sharpy/linear/src/lingebm.py", line 1065, in update_matrices_time_scale
    self.Kstr = self.scaled_reference_matrices['K'] * time_ref ** 2
KeyError: 'K'
```

Potentially due to missing initial assignment. Potentially solved (?) by initial assignment if self.scaled_reference_matrices is empty:

```
    def update_matrices_time_scale(self, time_ref):

        try:
            cout.cout_wrap('Updating C and K matrices and natural frequencies with new normalised time...', 1)
        except ValueError:
            pass

        if not self.scaled_reference_matrices:
            print('self.scaled_reference_matrices is empty!')
            self.scaled_reference_matrices['C'] = self.Cstr.copy()
            self.scaled_reference_matrices['K'] = self.Kstr.copy()

        self.Kstr = self.scaled_reference_matrices['K'] * time_ref ** 2
        self.Cstr = self.scaled_reference_matrices['C'] * time_ref

        self.freq_natural *= time_ref
```

Please let me know if this is an adequate workaround.

**Comment by ngoiz** [comment]
Hi @outoforderdev,

I think that the error is actually intended. When you run the velocity analysis in asymptotic stability it is required that the UVLM is scaled such that the only thing that needs to be done for each speed is to reassemble the structural equations (which can be done quickly). In your case, since `ScalingDict` is commented out, the UVLM system is not scaled and thus the `scaled_reference_matrices` are unset. The reason being that you cannot use the velocity analysis feature from AsymptoticStability with a dimensional UVLM. If you want to keep everything dimensional you need to run a SHARPy case every time changing the speed.

That said, the error you are getting is meaningless so I will put a check to ensure that you have scaled the UVLM before running the velocity analysis and otherwise spit out an error saying you need to scale it before using that feature.

Let me know if this makes sense or I am missing something.

Thanks for raising this, I will include the check in AsymptoticStability in any case.

**Comment by ngoiz** [comment]
Error message added and now available on the develop branch. It will be included in the next SHARPy release.

Thanks!

**Comment by outoforderdev** [comment]
Hello Norberto,

Thanks for addressing this.

So if I want to keep my system not scaled (normalized) and non-dimensional, should I set all scaling values to 1, do I understand this correctly?

Kind regards,
Mark

On 25 Feb 2020, at 15:06, Norberto Goizueta <notifications@github.com> wrote:

﻿

Hi @outoforderdev<https://github.com/outoforderdev>,

I think that the error is actually intended. When you run the velocity analysis in asymptotic stability it is required that the UVLM is scaled such that the only thing that needs to be done for each speed is to reassemble the structural equations (which can be done quickly). In your case, since ScalingDict is commented out, the UVLM system is not scaled and thus the scaled_reference_matrices are unset. The reason being that you cannot use the velocity analysis feature from AsymptoticStability with a dimensional UVLM. If you want to keep everything dimensional you need to run a SHARPy case every time changing the speed.

That said, the error you are getting is meaningless so I will put a check to ensure that you have scaled the UVLM before running the velocity analysis and otherwise spit out an error saying you need to scale it before using that feature.

Let me know if this makes sense or I am missing something.

Thanks for raising this, I will include the check in AsymptoticStability in any case.

**Comment by ngoiz** [comment]
To leave everything dimensional you should comment out the setting for the `ScalingDict` as you have here:
```
'aero_settings': {'dt': ws.dt,
    #                 'ScalingDict': {'length': 0.5 * ws.c_ref,
    #                 'speed': par.u_inf,
    #                 'density': par.rho},
```

That said, I'll case for the case where you set all scaling factors equal to 1, since that could trick the system.

In the meantime just comment it out (i.e. don't include the setting) to leave it dimensional
