### ISSUE TITLE
fatal error: mkl.h: No such file or directory

### ISSUE THREAD

**Issue by ljnpu** [ImperialCollegeLondon/sharpy#70]
Dear developers,

I try to compile sharpy according to the installation guide.
Everything goes well until the compilation of UVLM.

The information is given as follows:

(sharpy_env) lj@lj:~/code/UVLM$ ./run_make.sh 
mkdir -p lib
make -C src/
make[1]: Entering directory '/home/lj/code/UVLM/src'
g++ -fPIC -O3 -march=x86-64 -std=c++14 -DEIGEN_USE_MKL_ALL -I/home/lj/anaconda3/envs/sharpy_env/include -I/home/lj/anaconda3/envs/sharpy_env/include/eigen3 -fomit-frame-pointer -ffast-math -fopenmp -I../include -c cpp_interface.cpp
In file included from /home/lj/anaconda3/envs/sharpy_env/include/eigen3/Eigen/Core:100:0,
                 from /home/lj/anaconda3/envs/sharpy_env/include/eigen3/Eigen/Dense:1,
                 from /home/lj/anaconda3/envs/sharpy_env/include/eigen3/Eigen/Eigen:1,
                 from ../include/EigenInclude.h:11,
                 from ../include/cpp_interface.h:2,
                 from cpp_interface.cpp:1:
/home/lj/anaconda3/envs/sharpy_env/include/eigen3/Eigen/src/Core/util/MKL_support.h:58:13: fatal error: mkl.h: No such file or directory
 #   include <mkl.h>
             ^~~~~~~
compilation terminated.
Makefile:56: recipe for target 'cpp_interface.o' failed
make[1]: *** [cpp_interface.o] Error 1
make[1]: Leaving directory '/home/lj/code/UVLM/src'
Makefile:9: recipe for target 'default' failed
make: *** [default] Error 2
cp: cannot stat 'lib/*': No such file or directory

I have installed MKL successfully by using the command "conda install -c anaconda mkl".
But I don't know why the error still happens?
Could you help me on this issue?

Thanks and best regards,
LJ

**Comment by ArturoMS13** [comment]
Hi ljnpu,
are you following the latest installation instructions in https://ic-sharpy.readthedocs.io/en/latest/content/installation.html?

**Comment by ljnpu** [comment]
Thanks for your reply, dear ArturoMS13.

I use the guide from the following link:
https://ic-sharpy.readthedocs.io/en/dev_multibody/content/installation.html
The Last revision is 30 August 2019.

You mean I need to follow the latest instructions?
Thanks again.

**Comment by ljnpu** [comment]
It works！
Although there is still a warning related with MKL, sharpy can be successfully installed.

Thanks, dear friend!

**Comment by ljnpu** [comment]
There is something wrong during the SHARPY running.
Maybe I have to solve the MKL warning so as to compile SHARPY successfully.

Here is the Cmake message:
(sharpy_env) lj@lj:~/sharpy/build$ cmake ..
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The Fortran compiler identification is GNU 7.5.0
-- Check for working Fortran compiler: /usr/bin/gfortran
-- Check for working Fortran compiler: /usr/bin/gfortran  -- works
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Checking whether /usr/bin/gfortran supports Fortran 90
-- Checking whether /usr/bin/gfortran supports Fortran 90 -- yes
-- Could NOT find MKL (missing: MKL_LIBRARIES MKL_INCLUDE_DIRS MKL_INTERFACE_LIBRARY MKL_SEQUENTIAL_LAYER_LIBRARY MKL_CORE_LIBRARY) 
-- Looking for Fortran sgemm
-- Looking for Fortran sgemm - not found
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Looking for Fortran sgemm
-- Looking for Fortran sgemm - found
-- Found BLAS: /home/lj/anaconda3/envs/sharpy_env/lib/libblas.so  
-- Looking for Fortran cheev
-- Looking for Fortran cheev - found
-- A library with LAPACK API found.
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP_Fortran: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- Could NOT find MKL (missing: MKL_LIBRARIES MKL_INCLUDE_DIRS MKL_INTERFACE_LIBRARY MKL_SEQUENTIAL_LAYER_LIBRARY MKL_CORE_LIBRARY) 
-- A library with LAPACK API found.
-- Found OpenMP_C: -fopenmp  
-- Found OpenMP_CXX: -fopenmp  
-- Found OpenMP: TRUE   
-- Configuring done

PS: I have installed the MKL via "conda install -c anaconda mkl".
The location of MKL is "/home/lj/anaconda3/pkgs/mkl-2019.4-243/
"
Thanks for your help!

**Comment by ljnpu** [comment]
Is it because the -mkl flag only works with Intel compilers?
PS: I use the default GNU compiler and follow the latest installation guide.

**Comment by ArturoMS13** [comment]
Hi,

Can you give us more information about this?

You say that "There is something wrong during the SHARPY running." but you only attach the output of the cmake command. What are you trying to run and what is the error?

Did SHARPy compile successfully? 

Best regards

**Comment by ljnpu** [comment]
Sorry for the delay reply.
I installed Intel fortran and compiled it without any warning in the end.
Maybe the warning can be neglected.
I am not sure.
