### ISSUE TITLE
airfoil_info for wind turbine blade definition

### ISSUE THREAD

**Issue by kkpal3** [ImperialCollegeLondon/sharpy#84]
Hi, I ran the NREL 5MW wind turbine example and it worked like a charm. Now I'm trying to understand the airfoil_info page of the excel file for this example

%%%%%%%%%%%%%%%%%%%%

Name | Thickness
-- | --
[-] | [%]
vec_str | vec_float
cylinder | 100
DU40 | 60
DU35 | 39.6
DU30 | 34.6
DU25 | 30
DU21 | 24
NACA64 | 18

%%%%%%%%%%%%%%%%%%%%

What do the values of right column mean? Is that the accumulated percentage of each airfoil shape occupies along the span starting from the wing tip? According to the NREL 5 MW WT definition, it does not seem to be the case.

**Comment by ArturoMS13** [comment]
Hi kkpal3, thank you for the feedback.

It is the maximum thickness of the airfoil with respect to the chord, check the following image:
https://en.wikipedia.org/wiki/File:Wing_profile_nomenclature.svg 
Actually, it is nothing but the standard definition given for example in the definition of the NREL 5MW or in: Abbott, I. H. Theory of wing sections : including a summary of airfoil data. Dover, 1959

The use on UVLM is a bit tricky. First, the airfoils (cylinder, DU40 ...) have certain properties (camber, CL, CD ...). Second, wind turbine blades have varying thickness along the span (check the aero_blade sheet in the excel file). There are some blade sections with thickness that do not appear in the previous table. in these cases, the properties (camber, CL, CD ...) are assigned to those sections as a linear interpolation based on the airfoil thickness. 

In the master branch, it is only used to define the camber of the blade as UVLM does not account for thickness itself.

I hope this is useful. 
Best regards, Arturo.

**Comment by kkpal3** [comment]
Thank you Arturo for the clarification. 
I have another confusion on the excel data sheet. How are the different airfoil shapes assigned to different sections of the wind turbine blade?

**Comment by ArturoMS13** [comment]
Hi,

they are assigned by linear interpolation. Each airfoil in the "airfoil_info" shape has to have the associated coordinates in the "airfoil_coord" sheet. It is easy to see thought the headers.

After that, each section in the blade ("aero_balde" sheet) has a thickness. The shape of each section are obtained through interpolation among the available information in "airfoil_info" and the associated shape in "airfoil_coord".

This is conceptually what is done. However, the specific details are tricky. If you want me to be more specific about some point, let me know or you can go through them in the code if you feel comfortable.

Best regards, Arturo
